import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Image from "next/image";
import Sidebar from "@/components/Sidebar";
import Explorer from "@/components/Explorer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
          <Navbar />
        <div className="flex bg-[#1e1e1e] ">
  <aside className="">
   
              <Sidebar />

    <Explorer />
  </aside>
   
  <main className="p-8 text-[#e1e4e8] font-['JetBrains_Mono',monospace] flex-1 h-[85vh]  scroll-smooth overflow-x-hidden flex items-center content-area sm:p-4">
    
    {children}
  </main>
</div>

      </body>
    </html>
  );
}
